# CMake generated Testfile for 
# Source directory: /home/ulins/tempura/src/symbolic3
# Build directory: /home/ulins/tempura/build-asan/src/symbolic3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[symbolic3_basic_test]=] "/home/ulins/tempura/build-asan/src/symbolic3/symbolic3_basic_test")
set_tests_properties([=[symbolic3_basic_test]=] PROPERTIES  LABELS "symbolic3;base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;36;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_matching]=] "/home/ulins/tempura/build-asan/src/symbolic3/matching_test")
set_tests_properties([=[symbolic3_matching]=] PROPERTIES  LABELS "symbolic3;base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;42;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_pattern_binding]=] "/home/ulins/tempura/build-asan/src/symbolic3/pattern_binding_test")
set_tests_properties([=[symbolic3_pattern_binding]=] PROPERTIES  LABELS "symbolic3;base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;47;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_composable_predicates]=] "/home/ulins/tempura/build-asan/src/symbolic3/composable_predicates_test")
set_tests_properties([=[symbolic3_composable_predicates]=] PROPERTIES  LABELS "symbolic3;base;predicates" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;53;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_derivative]=] "/home/ulins/tempura/build-asan/src/symbolic3/derivative_test")
set_tests_properties([=[symbolic3_derivative]=] PROPERTIES  LABELS "symbolic3;calculus" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;63;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_evaluate]=] "/home/ulins/tempura/build-asan/src/symbolic3/evaluate_test")
set_tests_properties([=[symbolic3_evaluate]=] PROPERTIES  LABELS "symbolic3;calculus" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;69;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_simplification_basic]=] "/home/ulins/tempura/build-asan/src/symbolic3/simplification_basic_test")
set_tests_properties([=[symbolic3_simplification_basic]=] PROPERTIES  LABELS "symbolic3;consolidated;simplification" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;79;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_simplification_advanced]=] "/home/ulins/tempura/build-asan/src/symbolic3/simplification_advanced_test")
set_tests_properties([=[symbolic3_simplification_advanced]=] PROPERTIES  LABELS "symbolic3;consolidated;simplification" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;84;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_simplification_pipeline]=] "/home/ulins/tempura/build-asan/src/symbolic3/simplification_pipeline_test")
set_tests_properties([=[symbolic3_simplification_pipeline]=] PROPERTIES  LABELS "symbolic3;consolidated;simplification" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;89;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_two_stage_simplify]=] "/home/ulins/tempura/build-asan/src/symbolic3/two_stage_simplify_test")
set_tests_properties([=[symbolic3_two_stage_simplify]=] PROPERTIES  LABELS "symbolic3;simplification" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;95;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_oscillation_prevention]=] "/home/ulins/tempura/build-asan/src/symbolic3/oscillation_prevention_test")
set_tests_properties([=[symbolic3_oscillation_prevention]=] PROPERTIES  LABELS "symbolic3;simplification;stability" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;101;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_term_ordering]=] "/home/ulins/tempura/build-asan/src/symbolic3/term_ordering_test")
set_tests_properties([=[symbolic3_term_ordering]=] PROPERTIES  LABELS "symbolic3;term_structure;simplification" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;111;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_mult_ordering]=] "/home/ulins/tempura/build-asan/src/symbolic3/mult_ordering_test")
set_tests_properties([=[symbolic3_mult_ordering]=] PROPERTIES  LABELS "symbolic3;term_structure;simplification" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;117;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_term_structure]=] "/home/ulins/tempura/build-asan/src/symbolic3/term_structure_test")
set_tests_properties([=[symbolic3_term_structure]=] PROPERTIES  LABELS "symbolic3;term_structure" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;123;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_sophisticated_sorting_demo]=] "/home/ulins/tempura/build-asan/src/symbolic3/sophisticated_sorting_demo")
set_tests_properties([=[symbolic3_sophisticated_sorting_demo]=] PROPERTIES  LABELS "symbolic3;demo" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;129;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_fraction]=] "/home/ulins/tempura/build-asan/src/symbolic3/fraction_test")
set_tests_properties([=[symbolic3_fraction]=] PROPERTIES  LABELS "symbolic3;exact_math" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;139;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_exact_division]=] "/home/ulins/tempura/build-asan/src/symbolic3/exact_division_test")
set_tests_properties([=[symbolic3_exact_division]=] PROPERTIES  LABELS "symbolic3;exact_math" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;145;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_hyperbolic]=] "/home/ulins/tempura/build-asan/src/symbolic3/hyperbolic_test")
set_tests_properties([=[symbolic3_hyperbolic]=] PROPERTIES  LABELS "symbolic3;transcendental" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;151;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_debug]=] "/home/ulins/tempura/build-asan/src/symbolic3/debug_test")
set_tests_properties([=[symbolic3_debug]=] PROPERTIES  LABELS "symbolic3;utilities" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;157;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_operator_display]=] "/home/ulins/tempura/build-asan/src/symbolic3/operator_display_test")
set_tests_properties([=[symbolic3_operator_display]=] PROPERTIES  LABELS "symbolic3;display" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;163;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_to_string]=] "/home/ulins/tempura/build-asan/src/symbolic3/to_string_test")
set_tests_properties([=[symbolic3_to_string]=] PROPERTIES  LABELS "symbolic3;string_conversion;utilities" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;169;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
add_test([=[symbolic3_pretty_print]=] "/home/ulins/tempura/build-asan/src/symbolic3/pretty_print_test")
set_tests_properties([=[symbolic3_pretty_print]=] PROPERTIES  LABELS "symbolic3;printing;macros" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/symbolic3/CMakeLists.txt;175;add_test;/home/ulins/tempura/src/symbolic3/CMakeLists.txt;0;")
