# CMake generated Testfile for 
# Source directory: /home/ulins/tempura/src
# Build directory: /home/ulins/tempura/build-asan/src
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[chebyshev_test]=] "/home/ulins/tempura/build-asan/src/chebyshev_test")
set_tests_properties([=[chebyshev_test]=] PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/CMakeLists.txt;162;add_test;/home/ulins/tempura/src/CMakeLists.txt;0;")
add_test([=[broadcast_array_test]=] "/home/ulins/tempura/build-asan/src/broadcast_array_test")
set_tests_properties([=[broadcast_array_test]=] PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/CMakeLists.txt;167;add_test;/home/ulins/tempura/src/CMakeLists.txt;0;")
add_test([=[image_test]=] "/home/ulins/tempura/build-asan/src/image_test")
set_tests_properties([=[image_test]=] PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/CMakeLists.txt;172;add_test;/home/ulins/tempura/src/CMakeLists.txt;0;")
add_test([=[polynomial_test]=] "/home/ulins/tempura/build-asan/src/polynomial_test")
set_tests_properties([=[polynomial_test]=] PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/CMakeLists.txt;177;add_test;/home/ulins/tempura/src/CMakeLists.txt;0;")
add_test([=[json_test]=] "/home/ulins/tempura/build-asan/src/json_test")
set_tests_properties([=[json_test]=] PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/CMakeLists.txt;182;add_test;/home/ulins/tempura/src/CMakeLists.txt;0;")
add_test([=[sequence_test]=] "/home/ulins/tempura/build-asan/src/sequence_test")
set_tests_properties([=[sequence_test]=] PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/CMakeLists.txt;187;add_test;/home/ulins/tempura/src/CMakeLists.txt;0;")
add_test([=[root_finding_test]=] "/home/ulins/tempura/build-asan/src/root_finding_test")
set_tests_properties([=[root_finding_test]=] PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/CMakeLists.txt;192;add_test;/home/ulins/tempura/src/CMakeLists.txt;0;")
add_test([=[interpolate_test]=] "/home/ulins/tempura/build-asan/src/interpolate_test")
set_tests_properties([=[interpolate_test]=] PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "/home/ulins/tempura/src/CMakeLists.txt;197;add_test;/home/ulins/tempura/src/CMakeLists.txt;0;")
subdirs("symbolic3")
subdirs("bayes")
subdirs("matrix2")
subdirs("matrix3")
subdirs("meta")
subdirs("math")
subdirs("optimization")
subdirs("quadature")
subdirs("simd")
subdirs("special")
subdirs("synchronization")
subdirs("task")
subdirs("utility")
